### ISSUE TITLE
Explain how to get passed the "don't run"-dialog to ther "run anyway"-button

### ISSUE THREAD

**Issue by bjornregnell** [michelou/wix-examples#1]
Problem: This dialog can be intimidating to beginners:
![dont-run](https://user-images.githubusercontent.com/3601817/143769305-67a7ee42-8193-48c2-909e-418e463d1a8f.PNG)

Solution 1: Include the above an below images with explanations on how to install Scala anyway, namely by clicking the "more info"-link in the dialog to reveal the button (this is by no means obvious to a beginner, as more info does not seem to mean run anyway, and people might think that the installer is dangerous in some way and just cancel the instalation):

![run-anyway](https://user-images.githubusercontent.com/3601817/143769368-dd56b8d2-309d-4548-b1b0-f5e8637add6d.PNG)

Solution 2 (even better but more complicated): sign the install-app and make the intimidating warning go away.

**Comment by michelou** [comment]
@bjornregnell Thanks for your feedback ! 

The post [*WIX-Installer MSI Publisher Unknown*](https://stackoverflow.com/questions/17589754/wix-installer-msi-publisher-unknown) on StackOverflow gives some elements of answer to that concern.

I'll take some time in the next days to experiment with the [`signtool`](https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe) and [`insignia`](https://wixtoolset.org/documentation/manual/v3/overview/insignia.html) tools and will report progress.

**Comment by bjornregnell** [comment]
Yeah, signing if possible would be great. But in the mean time, before that long-term solution is available, I think it is good enough to release with explanations in order to get end-users to test and give feedback. Just let me know when you think a beta is ready to be tested by my students.

**Comment by michelou** [comment]
The MSI files available from the [Releases](https://github.com/michelou/wix-examples/releases) page are now *self-signed*, **BUT** this improvement *is not enough* to get rid of the two SmartScreen windows above.

The only way to obtain a valid publisher name (currently : "*Unknown publisher*") is to subscribe to a code signing certificate, for instance :

| Company | Type | 1-Year<br/>Subscription | 3-Year<br/>Subscription |
|:-----------|:------|:------------------|:------------------- |
|  [Certum](https://shop.certum.eu/) | [***open-source***](https://shop.certum.eu/open-source-code-signing-code.html) | $25.00/year | - |
|  [Certum](https://shop.certum.eu/) | [standard](https://shop.certum.eu/standard-code-signing-code.html) | $139.00/year | $109.66/year |
| [K&nbsp;Software](https://www.ksoftware.net/) | [standard](https://shop.certum.eu/standard-code-signing-code.html)  | $84.00/year<br/>| $69.66/year |
| [Sectigo](https://sectigo.com/) | [standard](https://sectigo.com/ssl-certificates-tls/code-signing) | $179.00/year | $166.00/year |

**Comment by michelou** [comment]
@bjornregnell What do you think of the updated [Releases](https://github.com/michelou/wix-examples/releases) page (with solution 1) ?!

**Comment by bjornregnell** [comment]
Thanks for the reminder @michelou -- I'll take a look at it later to night.

**Comment by bjornregnell** [comment]
(Sorry for the delay.) The page looks great!! Very informative. Do you want me to ask my students to test it? @michelou

**Comment by bjornregnell** [comment]
The actual release notes might be a bit daunting for a complete beginner programmer, but I guess they will just skip the things they don't understand and the text is useful for the informed users. Perhaps the text above the link to the link to release notes "Please read the following documents before running the Windows installer." can be interpreted as that you must understand what it means before you run it, so perhaps change that text to "More details are available here:" (or something similar ).

**Comment by michelou** [comment]
@bjornregnell I know... finding the right mix for end user and developer release notes isn't easy.
I've updated the [Releases](https://github.com/michelou/wix-examples/releases) page according to your last remark.

**PS.**  The availability of (at least) two versions for Scala 2 (i.e. [`scala-2.12.15.msi`](https://github.com/michelou/wix-examples/releases/tag/scala-2.12.15.msi) and [`scala-2.13.7.msi`](https://github.com/michelou/wix-examples/releases/tag/scala-2.13.7.msi)) respectively Scala 3 ([`scala3-3.0.2.msi`](https://github.com/michelou/wix-examples/releases/tag/scala3-3.0.2.msi) and [`scala3-3.1.0.msi`](https://github.com/michelou/wix-examples/releases/tag/scala3-3.1.0.msi)) makes it possible to test the 3 upgrade rules described in the  release notes.

**Comment by bjornregnell** [comment]
Looks great! I think this is ready for official release, perhaps after sources are included so that the scala API is available in Metals etc. (Is there some env-variable that needs to be set in order for the soruces to be shown or is SCALA_HOME or what it is called already in the installer steps?)

**Comment by michelou** [comment]
@bjornregnell Can we close this issue ?!

**NB.** `.msi` files available on the [Releases](https://github.com/michelou/wix-examples/releases) page now include the API documentation (~600 MB for Scala 2 once extracted... you're warned !).

Concerning the Scala API sources I guess you mean the Scala 3 Windows installer should provide them as JAR files, in a similar way as [`scala-docs-2.13.7.zip`](https://scala-lang.org/files/archive/) ?
<pre>
<b>&gt; dir /b c:\temp\scala-2.13.7\api\jars</b>
jline-3.20.0-javadoc.jar
jna-5.8.0-javadoc.jar
scala-compiler-2.13.7-javadoc.jar
scala-library-2.13.7-javadoc.jar
scala-reflect-2.13.7-javadoc.jar
scalap-2.13.7-javadoc.jar
</pre>

Please open another issue for adding the Scala API sources.

**Comment by bjornregnell** [comment]
Great! Yes, closing this seems good. I opened this issue for discussing API-sources for Scala and Java in relation to IDE:s such as vscode+Metals.
