### ISSUE TITLE
Include Scala 3 API sources to enable Metals doc hover etc

### ISSUE THREAD

**Issue by bjornregnell** [michelou/wix-examples#2]
I'm unsure how Metals picks up the sources and what is needed for the msi install to enable that Metals can use sources, but i think it would be good if the right env-variables or whatever is needed is done by the installer so that Metals cool debugging and doc features that needs API sources and Java sources "just works".

**Comment by michelou** [comment]
@bjornregnell Scala binaries, sources and javadocs are available as `.jar` files from the Maven Central repository [`org/scala-lang`](https://repo1.maven.org/maven2/org/scala-lang/), e.g.
- Scala 2.13.7 : [`scala-compiler`](https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.13.7/), [`scala-library`](https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.7/), [`scala-reflect`](https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.13.7/)
- Scala 3.1.0&ensp; : [`scala3-compiler`](https://repo1.maven.org/maven2/org/scala-lang/scala3-compiler_3/3.1.0/), [`scala3-library`](https://repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.1.0/), [`scala3-interfaces`](https://repo1.maven.org/maven2/org/scala-lang/scala3-interfaces/3.1.0/)

As I understand the process, [Metals](https://scalameta.org/metals) knows how to fetch those `.jar` files.

**PS.** [Metals](https://scalameta.org/metals) (Scala language server for IDEs) depends on [Bloop](https://scalameta.org/metals/docs/build-tools/bloop) (JVM-based build server) to compile a Scala project; they communicate together via the [Build Server Protocol (BSP)](https://github.com/scalacenter/bsp) (client-server relation).

**Comment by michelou** [comment]
@bjornregnell Can we close this issue ?!

**PS.** I've updated [`scala3-3.0.2.msi`](https://github.com/michelou/wix-examples/releases/tag/scala3-3.0.2.msi) and [`scala3-3.1.0.msi`](https://github.com/michelou/wix-examples/releases/tag/scala3-3.1.0.msi) on the [Releases](https://github.com/michelou/wix-examples/releases) page; both now include the API documentation packaged similarly to the Scala 2 Windows installers.

**Comment by bjornregnell** [comment]
Great with API included!
